server:
  port:8080

spring:
  application:
    name: 'Learn Camel'
    version: '1.0'
  rabbitmq:
    host: localhost
    username: rabbitmq
    password: rabbitmq

claro:
  api:
    path: '/api/v1/services'

camel:
  springboot:
    name: ServicesRest
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s